/*
 * JSP generated by Resin-3.0.28 (built Mon, 18 May 2009 02:16:38 PDT)
 */

package _jsp._web_22dinf._jsp._sys;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _list__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_0 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.include("../include/header.jsp", true);
      out.write(_jsp_string1, 0, _jsp_string1.length);
      if (_jsp_loop_0 == null)
        _jsp_loop_0 = new com.caucho.jsp.IteratorLoopSupportTag();
      java.util.Iterator _jsp_iter_1 = com.caucho.jstl.el.ForEachTag.getIterator(_caucho_expr_0.evalObject(pageContext));
      _jsp_loop_0.init(0, Integer.MAX_VALUE, 1);
      Object _jsp_oldVar_1 = pageContext.getAttribute("system");
      while (_jsp_iter_1.hasNext()) {
        Object _jsp_i_1 = _jsp_iter_1.next();
        pageContext.setAttribute("system", _jsp_i_1);
        _jsp_loop_0.setCurrent(_jsp_i_1, _jsp_iter_1.hasNext());
        out.write(_jsp_string2, 0, _jsp_string2.length);
        _caucho_expr_1.print(out, pageContext, false);
        out.write(_jsp_string3, 0, _jsp_string3.length);
        _caucho_expr_2.print(out, pageContext, false);
        out.write(_jsp_string4, 0, _jsp_string4.length);
        _caucho_expr_3.print(out, pageContext, false);
        out.write(_jsp_string5, 0, _jsp_string5.length);
        _caucho_expr_3.print(out, pageContext, false);
        out.write(_jsp_string6, 0, _jsp_string6.length);
        _caucho_expr_4.print(out, pageContext, false);
        out.write(_jsp_string7, 0, _jsp_string7.length);
        _caucho_expr_1.print(out, pageContext, false);
        out.write(_jsp_string8, 0, _jsp_string8.length);
        _caucho_expr_1.print(out, pageContext, false);
        out.write(_jsp_string9, 0, _jsp_string9.length);
      }
      pageContext.pageSetOrRemove("system", _jsp_oldVar_1);
      out.write(_jsp_string10, 0, _jsp_string10.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -4644494061398360982L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/jsp/sys/list.jsp"), 776705259591853234L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private final static com.caucho.el.Expr _caucho_expr_0 =
    new com.caucho.el.IdExpr("systems");
  private final static com.caucho.el.Expr _caucho_expr_1 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("system"), new com.caucho.el.StringLiteral("sysId")), "system.sysId");
  private final static com.caucho.el.Expr _caucho_expr_2 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("system"), new com.caucho.el.StringLiteral("name")), "system.name");
  private final static com.caucho.el.Expr _caucho_expr_3 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("system"), new com.caucho.el.StringLiteral("url")), "system.url");
  private final static com.caucho.el.Expr _caucho_expr_4 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("system"), new com.caucho.el.StringLiteral("introduce")), "system.introduce");

  private final static char []_jsp_string5;
  private final static char []_jsp_string10;
  private final static char []_jsp_string3;
  private final static char []_jsp_string7;
  private final static char []_jsp_string4;
  private final static char []_jsp_string8;
  private final static char []_jsp_string9;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  private final static char []_jsp_string6;
  static {
    _jsp_string5 = "\" target=\"_blank\">".toCharArray();
    _jsp_string10 = "\r\n	</table>\r\n</center>\r\n".toCharArray();
    _jsp_string3 = "/show\">".toCharArray();
    _jsp_string7 = "</td>\r\n				<td nowrap=\"nowrap\"><a href=\"/sys/".toCharArray();
    _jsp_string4 = "</a></td>\r\n				<td><a href=\"".toCharArray();
    _jsp_string8 = "\">\u4fee\u6539</a> <a\r\n					href=\"/relationship/".toCharArray();
    _jsp_string9 = "\">\u67e5\u770b\u8c03\u7528\u5173\u7cfb</a></td>\r\n			</tr>\r\n		".toCharArray();
    _jsp_string2 = "\r\n			<tr>\r\n				<td><a href=\"/sys/".toCharArray();
    _jsp_string1 = "\r\n<center>\r\n	<table>\r\n		<tr>\r\n			<td>\u7cfb\u7edf\u540d\u79f0</td>\r\n			<td>\u4e3b\u9875\u5730\u5740</td>\r\n			<td>\u7b80\u4ecb</td>\r\n			<td nowrap=\"nowrap\"><a href=\"/sys/new\">\u6dfb\u52a0</a></td>\r\n		</tr>\r\n		".toCharArray();
    _jsp_string0 = "\r\n\r\n".toCharArray();
    _jsp_string6 = "</a></td>\r\n				<td>".toCharArray();
  }
}
